<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1" elementFormDefault="unqualified" xmlns:sawsdl="http://www.w3.org/ns/sawsdl">
  <xs:complexType name="specimen_">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Specimen  - A material entity that is collected for potential use as an input upon which measurements or observations are performed.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" namespace="##other"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="specimen_" type="specimen_"/>
</xs:schema>
